"""
PolicyPulse backend configuration — loaded from environment variables.

===========================================================================
INTEGRATION GUIDE
===========================================================================

STATUS: 🟡 DEFAULTS ONLY — All API keys are empty strings.

All settings can be overridden via environment variables or a .env file
in the project root. Pydantic auto-maps env vars to field names
(case-insensitive). Example .env:

    OPENAI_API_KEY=sk-...
    GOOGLE_API_KEY=AIza...
    APERTURE_URL=http://aperture:8081

OWNER: Everyone — each team member sets keys for their module.
===========================================================================
"""

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    # --- LLM ---
    # 🔴 REQUIRED: At least one LLM key needed for agent pipeline.
    # OWNER: Rudra — set whichever LLM(s) you're using for agents.
    openai_api_key: str = ""       # For GPT-4 agent calls
    google_api_key: str = ""       # For Gemini agent calls
    anthropic_api_key: str = ""    # For Claude agent calls

    # --- Data APIs ---
    # 🟡 OPTIONAL: For enriching agent responses with real data.
    # These are NOT used yet — placeholders for when mock data is replaced.
    # OWNER: Rudra (RAG pipeline) — add keys as you integrate real sources.
    fred_api_key: str = ""         # Federal Reserve Economic Data
    bls_api_key: str = ""          # Bureau of Labor Statistics
    tavily_api_key: str = ""       # Tavily search API (for web research)

    # --- Lightning ---
    # 🟢 REAL: L402 payments handled entirely by lnget (lightning-agent-tools).
    # lnget reads its own config from ~/.lnget/config.yaml (generated by bootstrap).
    # OWNER: Praneeth — these defaults work for Docker regtest.
    aperture_url: str = "http://localhost:8081"  # Aperture L402 proxy
    lnget_max_cost_sats: int = 500               # Max auto-pay per request (sats)

    # --- App ---
    debug: bool = True
    # 🟡 HARDCODED: Update when frontend is deployed to a real URL.
    # OWNER: Samank — add your frontend's origin here.
    cors_origins: list[str] = ["http://localhost:3000"]

    model_config = {"env_file": ".env", "env_file_encoding": "utf-8"}


settings = Settings()
